# Generated by Django 5.0.2 on 2024-06-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('seccion', models.CharField(choices=[('habilidades_cognitivas', 'Habilidades Cognitivas'), ('habilidades_interpersonales', 'Habilidades Interpersonales'), ('rasgos_personalidad', 'Rasgos de Personalidad'), ('competencias_laborales', 'Competencias Laborales'), ('motivaciones_valores', 'Motivaciones y Valores'), ('adaptabilidad_flexibilidad', 'Adaptabilidad y Flexibilidad')], max_length=100)),
                ('tipo_respuesta', models.CharField(choices=[('a', 'Opción A (3 puntos)'), ('b', 'Opción B (2 puntos)'), ('c', 'Opción C (1 punto)')], max_length=1)),
            ],
        ),
    ]
