# Generated by Django 5.0.2 on 2024-06-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_remove_pregunta_tipo_respuesta_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.pregunta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='puntaje',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuesta.seccion'),
        ),
    ]
